# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

include:
  - r: release
  - r: oldrel
  - r: devel

bioc_packages:
  - BiocStyle
  - BiocParallel

r_packages:
  - covr

after_failure:
  find *Rcheck -name '*.fail' -print -exec cat '{}' \;

after_success:
  - Rscript -e 'covr::codecov()'
